### ISSUE TITLE
Empty configuration

### ISSUE THREAD

**Issue by evxjson** [clonemeagain/plugin-autocloser#13]
Hi!
The configuration page for the plugin is blank. I can see the following in the logs:

_PHP Fatal error:  Call to a member function get() on a non-object in /var/www/html/support/include/class.plugin.php on line 15, referer: http://support/scp/plugins.php_

osTicket version: 1.10.1
/Anders

**Comment by clonemeagain** [comment]
This might be related to changing the config as you've done in the other issue. You'll note the error is coming from the class.plugin.php core file, which does seem to indicate an error in the plugins config, however the change you made would actually fill the config with numbers rather than named configurations, so it either needs to be updated to PHP 5.6+ or the group config array needs to be properly unpacked into the global array before it's returned.

Likely relates to #12

**Comment by clonemeagain** [comment]
Hmm, you'll have to uninstall the plugin, upgrade (or rewrite the unpack), then reinstall. The config is stored in the database in a namespaced section of the config table, so it shouldn't affect anything else in the config, but the plugin won't work properly until fixed and reinstalled.

**Comment by clonemeagain** [comment]
Assuming resolved.

**Comment by evxjson** [comment]
Hi!
Thanks for your help. Resolved by upgrading to PHP7.

Best Regards
