### ISSUE TITLE
Plugin Not Working When Agent Answer Ticket from Email

### ISSUE THREAD

**Issue by tomzquad** [clonemeagain/plugin-autocloser#20]
Hi,

I tried the plugin and found some condition like When Agent Answer Ticket from Email so the plugin is not working.

Can you help me ?

Br,
Thomas

**Comment by clonemeagain** [comment]
Hi @tomzquad, 

First off, cheers for using my plugin mate!

Now, can you tell me more about how you've configured the plugin, and what you mean by "not working"? 

If I can't replicate the fault condition, I can't figure out how to fix it.

**Comment by tomzquad** [comment]
Hi @clonemeagain 

Thank you for replying me.

I configure the plugin like this.

![image](https://user-images.githubusercontent.com/32896238/34810934-b5306e00-f6d0-11e7-8890-707f83cfcb1e.png)

1. Agent Change the status to Resolved from web osticket
2. User reply the ticket from email, the status still Resolved
3. Agent reply the ticket from email, the status still Resolved
4. After couple days, The status still Resolved and not change to Closed

is that because the Agent reply from email so your plugin read as User ?
CMIIW

Please help.

br,
Thomas

**Comment by clonemeagain** [comment]
You have the option "Only change tickets with an Agent Response" ticked, so, you need an Agent to respond via osTicket for it to obey your instruction. If they respond/reply via email outside of osTicket, we have no way of knowing that, so wait for them to do so before acting. 
If you deselect that option, then it will simply wait for the 2 days you set and then change it, regardless of whether an agent has sent a response, as you've chosen a From status of "Resolved", we can reasonably assume the Agent has dealt with it to their satisfaction, so that should be fine mate.

**Comment by tomzquad** [comment]
Ok @clonemeagain Well noted with Thanks
