### ISSUE TITLE
Problema en la instalacion

### ISSUE THREAD

**Issue by sherreraautomata** [clonemeagain/plugin-autocloser#21]
Buen día Grizly,

Yo tengo OsTicket v.v1.10.1 (9ae093d)
Apache/2.4.7

Como comentaba, a la hora de la instalación del plugin deja de funcionar OsTicket y recurro a borrar el archivo y luego a eliminarlo en OsTicket.

Esto sucede para la version plugin-autocloser-1.1 pero no sucede en la version plugin-autocloser-1.0

---------------------------------------------------------------------------------------------------------

Good morning Grizly,

I have OsTicket v.v1.10.1 (9ae093d)
Apache / 2.4.7

As I was saying, at the time of installing the plugin, OsTicket stops working and I resort to deleting the file and then uninstalling it in OsTicket.

This happens for the plugin-autocloser-1.1 version but it does not happen in the plugin-autocloser-1.0 version

I want to install version 1.1, thanks.

**Comment by clonemeagain** [comment]
Hmm, thanks for the report mate. I'll check it out.

**Comment by jma83** [comment]
Any news? Same problem here. Seems to be related with database. When i remove autocloser row in plugins table, ostickets works again.

Thanks.

**Comment by clonemeagain** [comment]
Hey guys, sorry for the delay in looking into this, I've been flat out. One thing that might trigger the error immediately is the version of PHP, it requires 5.6+, mainly because the syntax used in the plugin was only introduced then. I would assume you've got that, using 1.10.1, however there's a chance you're not. 

If you could also post any log entries showing the fault, that would be really helpful. (ost debug mode logs, and apache server logs)

**Comment by jma83** [comment]
Finally It's solved for me. I've just updated php version to 5.6.31 and the plugin works fine in the lastest version. 

Thanks for this amazing plugin :)

**Comment by clonemeagain** [comment]
No worries mate! Thanks for using it. :+1:
