### ISSUE TITLE
[Feature Request] Language support

### ISSUE THREAD

**Issue by timfi** [clonemeagain/plugin-autocloser#5]
We have customers in different countries and it would be great if we could send them different kinds of autoreplies.

The way it would work for ex.: have two/multiple "from status" choices like "waiting for answer (DUTCH)" and waiting for answer (ENGLISH)" and give them different autoreply fields.

Or any alternative that would achieve this would also be great.

Thank you for this plugin BTW :)

**Comment by clonemeagain** [comment]
The lazy part of me would suggest just writing the message in both languages into the message box..
It works for some email newsletters I get. But it's not that great.

Ideally, if we wrote this, it would be dynamic, so if you or someone needed three, four, or many other custom notifications based on the source status, it could adapt.

I'm thinking it's possible, and not truly difficult, just inelegant. Then again, it's an offline plugin, so it doesn't matter that much if it's a bit less efficient.

I'm also thinking, if we're going down this road, why not go all the way?, "from status to status with messages and timeouts" could be bundled, add as many as you like, after adding each one a new set would appear, just delete all the fields to remove it.
From open to pending
From approved to finance required (maybe change department here.. hmm)
From finance approved to agent required (change department back, notify original agent)

Damn, that's basically a workflow manager. 

Hmm, what if we detected the tld of the users email address and sent them a custom message?
 .de gets German
 .nl gets Dutch..
Everyone else gets the English version.

less reliant on an agent manually setting the status first. 
Probably faster/easier to implement as well.
Just had a quick squiz, http://www.iana.org/domains/root/db strewth there's a few out!
Is that something that sounds useful? I'm just guessing if that would work, relies on people using country based email addresses.. unlike people, who use Gmail. Lol. Ok. Maybe the first one. 

Do you use input filters to detect languages? Can you? Dunno.
https://stackoverflow.com/a/18321862
Good thinking right there. Post a message once and include a link to translations. I like it. (Not just because lazy). 

Another option is using Canned Responses. If we defined a title format, something like: `:OpenStatusName: Closed Message Title`, then you could add as many you wanted, one for each status.
That way agents could manually trigger it before the timeout as well. Good for urgent tickets. Also non-admins could write the messages. I'm all for that. Let the sales folks write the marketing gibberish. 

Any of that sound good?

**Comment by timfi** [comment]
hi clonemeagain, thanks for effort :)

The problem with multilanguage replies is that is doesn't look personal. We have a very personal approach to our client and I think most of them don't even realize we use a ticketing system. We just want to send a "friendly" reminder that we haven't received a reply back.

Your first suggestion sounds perfect and I could see this be useful for other people too. This would mean just a small adjustment to our current workflow.

The all-the-way suggestion sounds great, but not for us :) I can imagine it over complicating the entire plugin though.

The TLD detection has the obvious gmail etc. problem like you said.
The language translation misses the personal touch :)

The canned responses idea sound good too. We actually generate the message titles ourself so we already have a good idea which language we're going to respond in, but the problem is that sometime we misjudge and have to adjust. For example: We think someone is speaks dutch, but they just live here and speak english. So our first reaction is Dutch and after we their reply we continue in English.

I think that for me the source status/custom notification is the best option and I also think this could be the most useful for other people. You could have a different "waiting for reply" status for sales and support and let each department set different auto replies.

I'm looking forward to your reaction, and while I'm not very experienced with PHP I'm very willing to put in some hours to make this work. If you could point me in the right direction that would be a great help.

BTW. I'm leaving on a holiday for a week tomorrow so might take a while to reply.

**Comment by clonemeagain** [comment]
Enjoy your holiday mate, I'll have a crack, then you can be a guinea pig, because testing is the hardest part. :-)

I'm inclined towards the canned responses side, because it makes it easier for me I think, and possibly easier for you.  Well, I'll chuck something together and see if it's good.

**Comment by clonemeagain** [comment]
I started a new branch to get the idea off the ground. It's pretty buggy thus far. I don't think osticket likes plugins changing their Config definition during the config process.. might have to move to hard code 10 groups in code, and let those who want to read the comment and edit the file suffer the rebuild..

Doesn't work yet, just letting you know I'm working on it.
https://github.com/clonemeagain/plugin-autocloser/tree/feature/link-status-to-canned-response

**Comment by timfi** [comment]
Hi, that sounds good :) I'm happy to help when you have something :)

**Comment by timfi** [comment]
Hi @clonemeagain,

Would it be possible to create multiple copies of the plugin to solve this problem. I know it sound a bit quick 'n dirty, but I just want something that does the trick.

I'd like someting like 4 version with 4 different from/to statusses and messages.

Thanks :)

**Comment by clonemeagain** [comment]
Well now, that's the kind out of the box thinking I like!
Shame it won't work though, not without rewriting a bunch of names.
My version is close enough, I'll just hard code 4 options with a warning next to the number. You should see it shit itself when you change the number though, funny. Add one group, lose all other settings back to default. (Just for the plugin).
I think it's the orm having a bit of a fit, because it needs to be saved twice before it applies, which should have been a clue that I'm doing something the wrong way.
My next plan was to simply bundle them all together as a big JSON string and build the admin interface in JavaScript, which is harder than it sounds without hacking at core.
I'm going to get on it today mate.

**Comment by clonemeagain** [comment]
OK, seems to work on mine, have a test mate (you've a backup right?)

https://github.com/clonemeagain/plugin-autocloser/archive/feature/link-status-to-canned-response.zip

Debugging is still on, because you'll want to see what it does. 

Basically, delete the original plugin, install that one, configure it. Each group is configurable, but the number of actions per group is set globally, not sure why I initially was going to use one number for all, like set it to 20 tickets, and if the first group needed 18 of those slots, then group two only had 2 available.. I still can, it's not bad. However, my test system has 100000+ open tickets, so, it never worked.. there was always more tickets to close. :-) 

It's not as fast as just changing the table values, however it does generate the emails. 
In tests with 150 matched tickets, it generated notes and thread entries while changing statuses to multiple different statuses in 20s.. not bad. Not something you'd want to run via auto-cron though. 

I need to update the README 

Checkout the global & group config:

![screenshot_2017-08-31_09-42-12](https://user-images.githubusercontent.com/5077391/29899757-bd94e6a6-8e30-11e7-84d0-13a06578acee.png)

And the next group, deliberately configured to try and compete with the first one: 
![screenshot_2017-08-31_09-42-32](https://user-images.githubusercontent.com/5077391/29899760-c216e328-8e30-11e7-8c94-b62e576b2ecd.png)

Yes, one can close them, another can open them! Not the best, but you can name them. Heck, because they are configured via db entries, you could theoretically script the change:
```echo "UPDATE ost_config SET value=1 WHERE key='group-enabled-1'" | mysql ```

Part of the scheduler could auto-enable the aging of tickets at 0900 and turn it off again at 1700.. would make it look like you're working when you're not. :+1:

**Comment by clonemeagain** [comment]
Heck, could even add an auto delete option, to purge ancient closed tickets. I've got an archive plugin that does that though, so no need to duplicate it.

I realise now that the second group message should say: `Auto opened for being closed too long` lol

**Comment by clonemeagain** [comment]
Ok, updated the sender code, so it actually sends as the assignee now, great. Not so great for unassigned tickets, then I noticed that for ancient tickets with assignee's long since Locked, notifications are still being sent.. so, turns out we can create an Agent account with whatever signature/picture/name we want, and simply use that to change all our tickets! Then simply Lock the robot account so nobody can log into it. 

AutoMod/TicketRobot/whatever. 

Alternatively, if you as admin want to be seen as incredibly productive, you can just use your own account, configure cron to only run during office hours, then be the office hero!

**Comment by timfi** [comment]
@clonemeagain, This looks great! Gonna test now and let you know. You're going to be our employee of the month :)

**Comment by timfi** [comment]
we would like to repeat our first response in one of the groups. Do you know the variable for this? %{message} and %{response} don't seem to work..

**Comment by clonemeagain** [comment]
It should be in the canned response config page.
I think you want %{ticket.thread.lastmessage} or original.. hmm, the first response? I don't think that's available, but we could add it! 
While we're playing with the VariableReplacer we can inject almost any variable.

**Comment by timfi** [comment]
Great! Where can I add this code or do I need a seperate plugin?

**Comment by clonemeagain** [comment]
Wrote something: https://github.com/clonemeagain/plugin-autocloser/blob/feature/link-status-to-canned-response/class.CloserPlugin.php#L353

I'm intrigued to see if the `%{wholethread}` idea works.. and if it includes all the attachments.

Ideally don't use it yet.. in theory, it shouldn't do anything until one of [these variables](https://github.com/clonemeagain/plugin-autocloser/blob/feature/link-status-to-canned-response/class.CloserPlugin.php#L311) get's added to a canned reply.. in theory. In practice it could be broken.

And I just typed my email address wrong twice, so, I'm not doing any more tonight.

**Comment by timfi** [comment]
Thanks mate! Will check out today. (it's 15:00 here :)) Goodnight!

**Comment by clonemeagain** [comment]
Sweeeet

It works. 

The available variables are `%{lastresponse}`, `%{firstresponse}` and `%{wholethread}`..

obviously injecting the whole thread has a bit of a performance hit.. but, fuck it. :1st_place_medal: Winning!

Check it out, quite clean:
```php
    /**
     * Fetches the last response sent to the ticket Owner.
     *
     * @param Ticket $ticket
     * @return string
     */
    private function fetchLastResponse(Ticket $ticket)
    {
        $response = $ticket->getResponses()
            ->order_by('created', QuerySet::DESC)
            ->first();
        if ($response instanceof AnnotatedModel) {
            if ($response->get('format') == 'text') {
                return "<br /><hr /><h3>{$response->get('title')}</h3><pre>{$response->get('body')}</pre>";
            }
            // Make prettier?
            return "<br /><hr /><h3>{$response->get('title')}</h3><p>{$response->get('body')}</p>";
        }
    }
 		
```

**Comment by timfi** [comment]
Ah very nice :+1: 

Consider this solved :)

We'd like to send you a fee, I'll contact you directly.

**Comment by clonemeagain** [comment]
Well, we can add additional details to the thread entries, like the date and time of the messages, might be useful. Perhaps by simply reusing the existing templates, so they are consistently formatted with other ticket notifications.
You like the robot idea? I've got a TicketRoomba now,, hoovering up old ticket crumbs, pretty fun.

Before merging though, I'll get in there and disable the debugging and update the readme.

**Comment by timfi** [comment]
haha lol, the robot looks alot better indeed. But since we only have one person on tickets it doesn't really matter.

**Comment by clonemeagain** [comment]
FYI: this has been merged
